-- SQLite schema for GameLauncher
CREATE TABLE IF NOT EXISTS Users (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  SteamId TEXT UNIQUE,
  NickName TEXT,
  SessionId TEXT,
  SessionExpiry DATETIME,
  FirstLaunch INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Characters (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  UserId INTEGER,
  Name TEXT,
  InternalName TEXT,
  AvatarId INTEGER,
  FOREIGN KEY(UserId) REFERENCES Users(Id)
);

CREATE TABLE IF NOT EXISTS Settings (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  UserId INTEGER,
  InstallPath TEXT,
  FOREIGN KEY(UserId) REFERENCES Users(Id)
);

CREATE TABLE IF NOT EXISTS Files (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  RelativePath TEXT,
  Size INTEGER,
  SHA256 TEXT
);
